baseURL: /
languageCode: en-us
title: Robinson Soccer
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  text: >-
    **Robinson City Park Fall League Registration opens June 1st - July 31st!**


    **Kids Soccer Camp May 29-June 2, 2023**


    [ï»¿Lincoln Trail College Soccer - Kids Summer Camp (Ages 4-8)](https://lincolntrailsoccer.totalcamps.com/shop/product/139393?fbclid=IwAR2Ki34rvRFYUgGdO7TXm8yFOnwnqVxh0BxXs9c0lV66PFmZcMwh0rnrsBY)
